{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: Role
metadata:
  name: {{ template "druid-operator.fullname" . }}
  labels:
    app: "{{ template "druid-operator.fullname" . }}"
    chart: "{{ include "druid-operator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - '*'
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - druid-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - druid.apache.org
  resources:
  - '*'
  verbs:
  - '*'
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
metadata:
  name: {{ template "druid-operator.fullname" . }}
  labels:
    app: "{{ template "druid-operator.fullname" . }}"
    chart: "{{ include "druid-operator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ template "druid-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "druid-operator.fullname" . }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "druid-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ template "druid-operator.fullname" . }}"
    chart: "{{ include "druid-operator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ end }}